export const SAVE_TABLE_NUMBER = 'SAVE_TABLE_NUMBER';
export const SAVE_DEVICE_UUID = 'SAVE_DEVICE_UUID';
export const SET_KITCHEN_VIEW = 'SET_KITCHEN_VIEW';
export const SAVE_USER_ID = 'SAVE_USER_ID';
export const SAVE_LOCATION_ID = 'SAVE_LOCATION_ID';
export const USER_AUTH_REQUEST = 'USER_AUTH_REQUEST';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
